apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\Projects\Sandbox\VideoPlatform\Dockers\local\kompose.exe convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: mongo:4.0.8
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
      hostname: mongo
      restartPolicy: Always
status: {}
